### ISSUE TITLE
Missing heatmap vis after importing latest version

### ISSUE THREAD

**Issue by aviationfan** [nin9s/elk-hole#10]
Could not locate that visualization (id: 0858a2c0-643d-11e9-b607-6710a00e4c3e) appears in the Dashboard in place of the heatmap.

**To Reproduce**
1. Removed all indexes to re-import the data, vis, and dashboard
2. Had Filebeat send logs
3. Imported v6.x vis > > elk-hole - vis.json
4. Imported v6.x dash > > elk-hole - dash.json
5. Navigate to dashboard
6. get the error Could not locate that visualization (id: 0858a2c0-643d-11e9-b607-6710a00e4c3e)

**Expected behavior**
Heat map shows the proper bubbles around the world

**Screenshots**
![dash_missing_vis](https://user-images.githubusercontent.com/955527/58968004-80e4a380-8772-11e9-9de1-b860f45d8efd.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser = Firefox 67.0

** ELK server stack
- Debian Linux
- Kibana 6.7.1

**Additional context**
Would it be possible to import just the 1 visualization without all of them as 1 json?  It seems like the combined JSON file is how Kibana manages it.

I only open this issue for those of us still on the V6 versions

**Comment by nin9s** [comment]
Yes it's possible to import just one. Let me check if I have the v6 version
flying around.
By the way, I remember it is possible to change the vis is manually. Could
you please check the id in the vis.json package file and change it to
0858a2c0-643d-11e9-b607-6710a00e4c3e

JJ Welch <notifications@github.com> schrieb am Mi. 5. Juni 2019 um 17:16:

**Comment by nin9s** [comment]
@aviationfan try this please

[DNSheatmap.zip](https://github.com/nin9s/elk-hole/files/3258298/DNSheatmap.zip)
