### ISSUE TITLE
import the template step unclear and not working as expected

### ISSUE THREAD

**Issue by aviationfan** [nin9s/elk-hole#11]
**Describe the bug**
I am not clear on step 14 in the instructions "import the template: paste the content of "logstash-syslog-dns-index.template_ELK7.x.json" into kibanas dev tools console"

What are the detailed steps to follow? Dev tools needs a command like PUT and an object definition to follow, e.g.
# index a doc
```
PUT index/type/1
{  
   "index_patterns":[  
      "logstash-syslog-dns*"
   ],
```

**To Reproduce**
Paste the JSON from `logstash-syslog-dns-index.template_ELK7.x.json` with no command and get an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
Kibana 7.1.1
Elasticsearch 7.1.1

**Comment by nin9s** [comment]
thanks, I've missed that
fixed it in https://github.com/nin9s/elk-hole/blob/master/json/logstash-syslog-dns-index.template_ELK7.x.json

**Comment by aviationfan** [comment]
PUT worked great
