### ISSUE TITLE
_grokparsefailure

### ISSUE THREAD

**Issue by nin9s** [nin9s/elk-hole#13]
for grok parse failures because I get a LOT of them. What I did with logstash is have it write out the event to a file so I can look at them and figure out what patterns might be missing. Like this:

```
output {
  if "_grokparsefailure" in [tags]{
    csv {
      fields => ["message"]
      path => "/Users/jjwelch/grokparsefailures.csv"
    }
  }
  else if "pihole" in [tags]{
    elasticsearch {
      hosts => ["mac-pro.house:9200"]
      user => "elastic"
      password => "Service.1"
      manage_template => false
      index => "logstash-syslog-dns-%{+YYYY.MM}"
    }
  }
}
```
I would be glad to submit the contents of that file so we can figure out the grok stuff that needs to be added. i have done some myself in my conf file as well

_Originally posted by @aviationfan in https://github.com/nin9s/elk-hole/issues/12#issuecomment-505955195_

**Comment by aviationfan** [comment]
Here is a zip file of the grokparsefailures that I have encountered spanning May 6 - June 14 or about 2 months. Also I am attaching my version of the logstash conf file where I added some of my own patterns to try and slurp up all of the pihole output. We could toss out some of the May 6 stuff because I think that was prior to changing the logging setup on the pihole install.

[grokparsefailures.csv.zip](https://github.com/nin9s/elk-hole/files/3331306/grokparsefailures.csv.zip)
[20-dns-syslog.conf.zip](https://github.com/nin9s/elk-hole/files/3331309/20-dns-syslog.conf.zip)

**Comment by nin9s** [comment]
As you stated we can ignore May 6th because piholes extra logging was disabled during that period, so its ok to fail - The same goes for Jun 2th and every other days where the requesting ip address does not appear in the log line

What I dont understand are the replys like:
`Jun  1 00:02:56 dnsmasq[25373]: reply time-osx.g.aaplimg.com is ntp minpoll 9 maxpoll 12 iburst`
the answer should be an ip address but it is not.

`Jun  1 01:39:18 dnsmasq[25373]: reply push.apple.com is count=50`
never seen this type

`Jun  1 15:56:46 dnsmasq[25373]: 154939   192.168.1.2/64230 forwarded [2620:100:601c:1::162.125.6.1] to 208.67.222.222`
Seriously, what is that? - [2620:100:601c:1::162.125.6.1] looks like a mix of v4 and v6

`Jun  2 15:13:04 dnsmasq[25373]: reply A7HVQ4GVB6D6YOUDKI7CSQNB3VZ2MCMKYVOGLADJGYGQPMFUA7EA.hash.pilot.ct.googleapis.com is 173682570
Jun  2 15:13:05 dnsmasq[25373]: reply   0.322442432.638678448.tree.pilot.ct.googleapis.com is ?
Jun    2 15:13:05 dnsmasq[25373]: reply   14.322442432.638678448.tree.pilot.ct.googleapis.com is
Jun    2 15:13:05 dnsmasq[25373]: reply   21.173682570.638678448.tree.pilot.ct.googleapis.com is }
Jun    2 15:13:05 dnsmasq[25373]: reply   28.173682570.638678448.tree.pilot.ct.googleapis.com is
Jun    2 15:13:05 dnsmasq[25373]: reply   7.322442432.638678448.tree.pilot.ct.googleapis.com is 4
`
well ... 

is the requesting host a mac? maybe its an apple specific thing? Do you know what their purpose?

**Comment by nin9s** [comment]
you dont need:

```
# piholed no source
          "^%{SYSLOGTIMESTAMP:date} %{SYSLOGPROG}: \/etc\/pihole\/gravity\.list %{FQDN:blocked_domain} is %{IP:pihole}$",
          # cached no source
          "^%{SYSLOGTIMESTAMP:date} %{SYSLOGPROG}: cached %{FQDN:domain_request} is %{IP:ip_response}$",

```

as long as you make sure https://github.com/nin9s/elk-hole/blob/master/dnsmasq.d/99-pihole-log-facility.conf is loaded properly.

**Comment by aviationfan** [comment]
I was reading something about a mix of v4 and v6 which would explain that weird pattern that you mention. 

The ones with count=50 are a mystery to me. I was wondering if the NTP server it's trying will deny after a certain number of requests? 

many macs in my setup so it could be any one of them

**Comment by nin9s** [comment]
in what context and where did you read v4/6 getting mixed?

the messages like `Jun  2 15:13:04 dnsmasq[25373]: reply .3473310.14825983.tree.digicert.ct.googleapis.com is pVf*` more look like somehow corrupted - cant imagine that dnsmasq would log such weird stuff

`Jun  7 14:07:58 dnsmasq[25373]: 336728 192.168.1.242/58021 forwarded https://notify.bugsnag.com/ to 208.67.220.220`

these will fail too of course

**Comment by nin9s** [comment]
```
C:\Users\nines>nslookup -query=txt push.apple.com
Server:  NS01.unimatrix01.local
Address:  192.168.254.251

Nicht autorisierende Antwort:
push.apple.com  text =

        "count=50"

push.apple.com  nameserver = a.ns.apple.com
push.apple.com  nameserver = b.ns.apple.com
push.apple.com  nameserver = c.ns.apple.com
push.apple.com  nameserver = d.ns.apple.com

```

So, this is legit and simply comes back as TXT. This needs to be implemented I guess.

**Comment by aviationfan** [comment]
I think I need to turn off ipv6 on that one Mac as it has an address but I don't allow ipv6 on my WAN ... yet

Asked the pihole group about this 
[https://discourse.pi-hole.net/t/seeing-entries-in-the-log-that-look-like-ipv6-mixed-with-ipv4/21124](url)

**Comment by nin9s** [comment]
I wonder if this could be the result of a dual stack request or something like that!? At least even umbrella does not understand this query :)

**Comment by ambron60** [comment]
Great job on this project! Unfortunately, mine pihole log had patterns unmatched by the .conf file, so grokparsefailures were all over the place :/

**Comment by nin9s** [comment]
thanks @ambron60 
con you give me one/some examples events please?

**Comment by ambron60** [comment]
Certainly, this is an example:

Nov 23 13:47:58 dnsmasq[3775]: 44734 192.168.1.219/42334 validation result is INSECURE

**Comment by nin9s** [comment]
theses are dnssec log entries. I've never had these events because my setup is like so:

client ->pihole(dnsmasq) -> unbound managing dnssec -> root servers/other authoritative name servers

so dnsmasq is not doing dnssec but unbound is!

depending on the actual count of these log lines we could write grok patterns or simply drop events where we find some unique strings

**Comment by ambron60** [comment]
I have others like so:
Nov 23 14:15:52 dnsmasq[3775]: Insecure DS reply received, do upstream DNS servers support DNSSEC?
and ..
Nov 23 14:15:52 dnsmasq[3775]: * 192.168.1.177/59993 reply 168.192.in-addr.arpa is BOGUS DS

I haven't finished setting up the dashboards or anything because the grok failures stopped me in my tracks ...

**Comment by nin9s** [comment]
I recommend choosing 1 of:

> drop events where we find some unique strings

or

> we could also grab everything not matched by a previous grokfilter by using `%{GREEDYDATA}` which is `.*`

I suppose you dont care if dnssec log events arent indexed to logstash do you?

**Comment by ambron60** [comment]
No.1 seems like less hassle.. i disabled DNSSSEC temporarily, but other messages aren't getting parsed as well. Interestingly, Kibana's only showing events with grokparsefailure, all other fields say:
This field is present in your Elasticsearch mapping but not in the 500 documents shown in the doc table. You may still be able to visualize or search on it.

**Comment by nin9s** [comment]
did you try to refresh the index field list?

**Comment by ambron60** [comment]
I did

**Comment by nin9s** [comment]
the error usually means there is no data in the fields for the specific timeframe. are you sure dnssec is disabled? did you try do debug to console? comment out stdout { codec => rubydebug } in the output section. as far as I remember the output goes to the default logstrash log file.

**Comment by ambron60** [comment]
I'll uncomment stdout and check.. yes DNSSEC is disabled.. no worries, I'll keep troubleshooting- I already have my honeypot in kibana, the pihole logs would be a nice-to-have kinda thing..

**Comment by nin9s** [comment]
if its not working please I'll be happy to help. Just open a separate issue so we dont mess everything up here :D
