### ISSUE TITLE
Heat map error: index pattern does not contain any of the following field types: geo_point

### ISSUE THREAD

**Issue by aviationfan** [nin9s/elk-hole#14]
**Describe the bug**
Heat map vis failing with an error
 No Compatible Fields: The logstash-syslog-dns* index pattern does not contain any of the following field types: geo_point 

**Screenshots**
![DNS_heatmap_-_pihole_-_Kibana](https://user-images.githubusercontent.com/955527/60982235-f7863b00-a2f4-11e9-97e7-1d5d33720fcf.png)

Why is geoip.location not found? I see it in some of the records in the JSON. I do not see it in my index pattern though.

**Comment by nin9s** [comment]
thank you again for your detailed testing @aviationfan !
I suspect it is generally found but not with the correct fied type geo_point so you see it in the jsons but kibana cant use it as a vis source for geographic data.

Please try the following template and test again. Do you have the geoip plugin enabled?

https://github.com/nin9s/elk-hole/pull/15/commits/726efb61c2198810d3479f7142e25548832554f9

**Comment by aviationfan** [comment]
Would that change to the template only affect new data or would it fix old data too?

**Comment by nin9s** [comment]
It would only affect a new index, New data in the existing index isn't sufficient.

Index templates are only applied during index creation unfortunately

**Comment by nin9s** [comment]
@aviationfan fixed?

**Comment by aviationfan** [comment]
Looks like the heatmap is working but other stuff may not be. I am seeing 79 fields in the index pattern, is that right?

![logstash-syslog-dns__-_Kibana](https://user-images.githubusercontent.com/955527/61339242-1bb4b100-a7fa-11e9-9222-5e1cf5675645.png)

**Comment by nin9s** [comment]
It’s difficult to answer (at least for me) if 79 are correct. I have 100 where 11 are conflicts produced by changes in the field types in the different indexes

Are you expecting something special to not work correctly?

I will clear all indexes but the latest and check back the field types counter

**Comment by nin9s** [comment]
79 fields is correct!

![image](https://user-images.githubusercontent.com/17455046/61354424-70940e00-a872-11e9-9ecb-aec43f8c7a4b.png)

**Comment by aviationfan** [comment]
Great, that matches then.
