### ISSUE TITLE
Logstash Error

### ISSUE THREAD

**Issue by apedance** [nin9s/elk-hole#2]
`[2019-03-30T14:46:11,266][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"LogStash::ConfigurationError", :message=>"Expected one of #, { at line 132, column 12 (byte 4121) after filter {\n  if \"pihole\" in [tags]{\n    grok {\n      patterns_dir => [\"/opt/bitnami/logstash/conf/patterns/\"]\n      match => {\n                \"message\" => [\n\n# request - query type\n \"^%{DNSMASQPREFIX} query\\[%{WORD:query_type}\\] %{FQDN:domain_request} from %{IP:request_from}$\",\n # reponse domain to ip\n \"^%{DNSMASQPREFIX} reply %{FQDN:domain_request} is %{IP:ip_response}$\",\n # response domain is NXDOMAIN\n \"^%{DNSMASQPREFIX} reply %{FQDN:domain_request} is NXDOMAIN$\",\n # response config domain is NXDOMAIN\n \"^%{DNSMASQPREFIX} config %{FQDN:domain_request} is NXDOMAIN$\",\n # response config domain is no-DATA\n \"^%{DNSMASQPREFIX} config %{FQDN:domain_request} is NODATA-IPv[4,6]$\",\n # reponse domain to ip cname\n \"^%{DNSMASQPREFIX} reply %{FQDN:domain_request} is \\<CNAME\\>$\",\n # respone ip to domain\n \"^%{DNSMASQPREFIX} reply %{IP:ip_request} is %{FQDN:domain_response}$\",\n # piholed\n \"^%{DNSMASQPREFIX} \\/etc\\/pihole\\/gravity\\.list %{FQDN:blocked_domain} is %{IP:pihole}$\",\n # piholed local\n \"^%{DNSMASQPREFIX} \\/etc\\/pihole\\/local\\.list %{FQDN:blocked_domain} is %{IP:pihole}$\",\n # blacklist\n \"^%{DNSMASQPREFIX} \\/etc\\/pihole\\/black\\.list %{FQDN:blocked_domain} is %{IP:pihole}$\",\n # reverse response etc hosts ip to domain\n \"^%{DNSMASQPREFIX} \\/etc\\/hosts %{IP:ip_request} is %{FQDN:domain_response}$\",\n # reverse response etc hosts domain to ip\n \"^%{DNSMASQPREFIX} \\/etc\\/hosts %{FQDN:domain_request} is %{IP:ip_response}$\",\n # forward dns to\n \"^%{DNSMASQPREFIX} forwarded %{FQDN:domain_request} to %{IP:dns_forward_to}$\",\n # cached domain to ip\n \"^%{DNSMASQPREFIX} cached %{FQDN:domain_request} is %{IP:ip_response}$\",\n # cached ip to domain\n \"^%{DNSMASQPREFIX} cached %{IP:ip_request} is %{FQDN:domain_response}$\",\n # cached domain to ip cname\n \"^%{DNSMASQPREFIX} cached %{FQDN:domain_request} is \\<CNAME\\>$\",\n # cached domain is NXDOMAIN\n \"^%{DNSMASQPREFIX} cached %{FQDN:domain_request} is NXDOMAIN$\",\n # cached domain is no-DATA\n \"^%{DNSMASQPREFIX} cached %{FQDN:domain_request} is NODATA-IPv[4,6]$\",\n # domain is no-DATA\n \"^%{DNSMASQPREFIX} reply %{FQDN:domain_request} is NODATA-IPv[4,6]$\",\n # SRV\n \"^%{DNSMASQPREFIX} query\\[%{WORD:query_type}\\] %{HOSTNAMEPTR:request} from %{IP:request_from}$\",\n # SRV forwarded\n \"^%{DNSMASQPREFIX} forwarded %{HOSTNAMEPTR:request} to %{IP:dns_forward_to}$\" \n\n                  ]\n      }\n}\n\n# to do cached and cached reverse\n\n\n      if [request_from] {\n        mutate {\n          add_tag => [ \"request and query type\" ]\n        }\n      }\n      else if [ip_response] {\n        mutate {\n          add_tag => [ \"response domain to ip\" ]\n        }\n      }\n      else if [message] =~ \"CNAME\" and [message] =~ \"reply\" {\n        mutate {\n          add_tag => [ \"response domain to ip CNAME\" ]\n        }\n      }\n      else if [domain_response] and [message] =~ \"reply\" {\n        mutate {\n          add_tag => [ \"response ip to domain\" ]\n        }\n      }\n      else if [blocked_domain] {\n        mutate {\n          add_tag => [ \"piholed\" ]\n        }\n      }\n      else if [message] =~ \"\\/etc\\/hosts\" {\n        mutate {\n          add_tag => [ \"reverse hostsfile\" ]\n        }\n      }\n      else if [dns_forward_to] {\n        mutate {\n          add_tag => [ \"dns forward\" ]\n        }\n      }\n      else if [ip_request] and [message] =~ \"cached\" {\n        mutate {\n          add_tag => [ \"cached ip to domain\" ]\n        }\n      }\n      else if [domain_request] and [message] =~ \"cached\" {\n        mutate {\n          add_tag => [ \"cached domain to ip\" ]\n        }\n      }\n      else if [message] =~ \"cached\" and [message] =~ \"CNAME\" {\n        mutate {\n          add_tag => [ \"cached domain to ip cname\" ]\n        }\n      }\n      else if [message] =~ \"cached\" and [message] =~ \"NXDOMAIN\" {\n        mutate {\n          add_tag => [ \"cached NXDOMAIN\" ]\n        }\n      }\n      else if [NODATA-IPv4] {\n        mutate {\n          add_tag => [ \"NODATA\" ]\n        }\n      }\n      else if [NODATA-IPv6] {\n        mutate {\n          add_tag => [ \"NODATA\" ]\n        }\n      }\n\n\t  reverse ", :backtrace=>["/opt/bitnami/logstash/logstash-core/lib/logstash/compiler.rb:41:in `compile_imperative'", "/opt/bitnami/logstash/logstash-core/lib/logstash/compiler.rb:49:in `compile_graph'", "/opt/bitnami/logstash/logstash-core/lib/logstash/compiler.rb:11:in `block in compile_sources'", "org/jruby/RubyArray.java:2577:in `map'", "/opt/bitnami/logstash/logstash-core/lib/logstash/compiler.rb:10:in `compile_sources'", "org/logstash/execution/AbstractPipelineExt.java:151:in `initialize'", "/opt/bitnami/logstash/logstash-core/lib/logstash/pipeline.rb:22:in `initialize'", "/opt/bitnami/logstash/logstash-core/lib/logstash/pipeline.rb:90:in `initialize'", "/opt/bitnami/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:43:in `block in execute'", "/opt/bitnami/logstash/logstash-core/lib/logstash/agent.rb:96:in `block in exclusive'", "org/jruby/ext/thread/Mutex.java:165:in `synchronize'", "/opt/bitnami/logstash/logstash-core/lib/logstash/agent.rb:96:in `exclusive'", "/opt/bitnami/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:39:in `execute'", "/opt/bitnami/logstash/logstash-core/lib/logstash/agent.rb:334:in `block in converge_state'"]}
`

**Comment by nin9s** [comment]
@apedance should be fixed now

https://github.com/nin9s/elk-hole/blob/master/logstash/conf.d/20-dns-syslog.conf
