### ISSUE TITLE
logstash configuration pattern file path mismatch

### ISSUE THREAD

**Issue by vakarthik** [nin9s/elk-hole#21]
In the file https://github.com/nin9s/elk-hole/blob/master/logstash/conf.d/20-dns-syslog.conf

Line no: 19
  patterns_dir => ["/etc/logstash/patterns/"]

It should have been
 patterns_dir => ["/etc/logstash/conf.d/patterns/"]

**Comment by nin9s** [comment]
thanks @vakarthik
