### ISSUE TITLE
Integration with Security Onion

### ISSUE THREAD

**Issue by klausagnoletti** [nin9s/elk-hole#32]
Hi

I am trying to get this to work with Security Onion (https://securityonion.net/). It turns out there is quite a strict format in order to get this working with the built-in Logstash - https://securityonion.readthedocs.io/en/latest/logstash.html. My experience here is really close to zero, so the reason to post it here would be to ask if anyone has any experience in doing this already? If not, I'll try myself to make it work 'the right way'. If I manage, I will be happy to share my modified logstash parsing files somehow. I am also quite a newbit at git, so not sure I'll be able to fork or whatever is technically needed, but we'll take that later :)

Thanks for your help - and for a great product!

/klaus

**Comment by klausagnoletti** [comment]
I have looked further into the issue and the error message that Logstash gives. The following gets repeated quite a lot in the log:

[2020-04-12T13:45:33,527][ERROR][logstash.javapipeline    ] Pipeline aborted due to error {:pipeline_id=>"main", :exception=>#<Grok::PatternError: pattern %{DNSMASQPREFIX} not defi
ned>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/jls-grok-0.11.5/lib/grok-pure.rb:123:in `block in compile'", "org/jruby/RubyKernel.java:1425:in `loop'", "/us
r/share/logstash/vendor/bundle/jruby/2.5.0/gems/jls-grok-0.11.5/lib/grok-pure.rb:93:in `compile'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-grok-4.2.0/lib/logstash/filters/grok.rb:284:in `block in register'", "org/jruby/RubyArray.java:1792:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-grok-4.2.0/lib/logstash/filters/grok.rb:278:in `block in register'", "org/jruby/RubyHash.java:1419:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-grok-4.2.0/lib/logstash/filters/grok.rb:273:in `register'", "org/logstash/config/ir/compiler/AbstractFilterDelegatorExt.java:56:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:192:in `block in register_plugins'", "org/jruby/RubyArray.java:1792:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:191:in `register_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:447:in `maybe_setup_out_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:204:in
`start_workers'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:146:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:105:in `block in
start'"], :thread=>"#<Thread:0x52b31441 run>"}
[2020-04-12T13:45:33,619][ERROR][logstash.agent           ] Failed to execute action {:id=>:main, :action_type=>LogStash::ConvergeResult::FailedAction, :message=>"Could not execute action: PipelineAction::Create<main>, action_result: false", :backtrace=>nil}

So somehow it is not very happy with DNSMASQPREFIX. I am unsure whether this is a result of an error in the custom pattern file - or because it for some weird reason can't include that file in the running configuration.

I will investigate further and update the issue as I go. Hope that is ok :). Logstash is running as a docker on Security Onion but has bind both configuration and log directories. So potentially this could also be a filepermissions issue.

Thanks

/k

**Comment by nin9s** [comment]
Hi Klaus

This should be no more than properly defining the pattern file as the error clearly indicates the pattern is unknown. 
Please let me know if you are not able to fix it so we can look closer

**Comment by klausagnoletti** [comment]
I found the error:
In Security Onion, the Logstash container's /usr/share/logstash/pipeline is mount bind as /etc/logstash/conf.d. The rest of the files and directories in /etc/logstash are either not mounted or mounted as specific files. So the only way for Logstash to know about the new patterns is to add another bind mount and add the path to that in the conf file as the container sees it. I will update when I have done this to my own environment. It will take a little while since I am not fluent in Docker :)

**Comment by klausagnoletti** [comment]
It works now. I had to remove the original conf file that starts up beats as well. 

By design Security Onion divides Logstash's config files into a few categories: input, preprocess, postprocess, output, so ideally the conf file you provided should be spilt as well. I will do that and attach it to this. Then I hope you will integrate it and write a summary of my posts in an FAQ for the next guy who wants to do the same :)

**Comment by klausagnoletti** [comment]
Allright. I now have a problem I have no idea how to fix. Pihole is now sending logs, filebeat gets them, sends them to logstash where logstash tries to index them. However, it can't as I can't find the index pattern in Kibana as you're described in the documentation.

When I investigate, I find this in the Logstash log:

[2020-04-13T08:06:25,710][WARN ][logstash.outputs.elasticsearch] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"logstash-syslog-dns
-2020.04", :_type=>"doc", :routing=>nil}, #<LogStash::Event:0x1334b135>], :response=>{"index"=>{"_index"=>"logstash-syslog-dns-2020.04", "_type"=>"doc", "_id"=>"EhGTcnEBNzemBVjPQq-
s", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse field [host] of type [text] in document with id 'EhGTcnEBNzemBVjPQq-s'", "caused_by"=>{"
type"=>"illegal_state_exception", "reason"=>"Can't get text on a START_OBJECT at 1:139"}}}}}

I have ni idea what "Can't get text on a START_OBJECT at 1:139" means or how to fix it. Do you?

Thanks! I am so close now :-P

/klaus

**Comment by nin9s** [comment]
What exact step doc wise are you currently stuck in? What do you mean by can't find the index pattern? Did you import it previously?

**Comment by klausagnoletti** [comment]
I am stuck in step 12.

First let me explain my setup. First of all, I am running pihole in a docker container on Raspbian. That proves to be a challenge since Beats is not officially supported on arm anymore - and also, it's in a container :-) Fortunately (in terms of the rpi part) a clever guy created easyBEATS (https://github.com/josh-thurston/easyBEATS) and another clever guy compiled raspbian packages and keeps an archive of the current flavors of *beats (currently v7.6. So I grabbed that and installed it and hoped that it work. I don't know if it supports older versions of ELK as well (Security Onion ships with ELK v6.8), so this could be the problem. But my lack of experience prevents me to find out myself.

After filebeats I adapted each of the steps in your guide so it fits Security Onion (mount binds and adapting conf files etc) and my pihole docker (mounting binds so I can access /etc/dnsmasq.d and /var/log on the docker host), adapting filebeats configuration appropriately.

Everything up until step 12 seems to work. Filebeats sees and parses pihole, connects to logstash and send logs.

Let me know what I can do to help you look into the issue. I am aware that this is a non-standard setup :) - but on the other hand, Security Onion is a genius product for people into infosec. And also, pihole is fantastic for - yes, an rpi. So I do indeed think it's a relevant setup so if we can make it work, I think and hope others could benefit as well.

Thanks a bunch for your help!

/klaus

**Comment by klausagnoletti** [comment]
I may have an idea to what could be wrong:

https://securityonion.readthedocs.io/en/latest/logstash.html#adding-new-logs-or-modifying-existing-parsing

Under 'Mapping Templates' it says that new fields that doesn't match the predefined templates aren't indexed - unless provided in a mapping template. So it seems like I need to create a custom mapping template. I'll investigate that and keep this thread updated.

**Comment by klausagnoletti** [comment]
Going forward with that idea, my plan is to modify the conf file so it has template support and modify the content of logstash-syslog-dns-index.template_ELK7.x.json and load that as a template in Security Onion.

The output part of the logstash conf file looks like this:
```
output {
#       stdout { codec => rubydebug }
        if "pihole" in [tags]{
                elasticsearch {
                        hosts => elasticsearch
                        template => "/logstash-syslog-dns-template.json"
                        template_name => "logstash-syslog-dns"
                        index => "logstash-syslog-dns-%{+YYYY.MM}"
                }
        }
}

```
I've copied the `logstash-syslog-dns-index.template_ELK7.x.json` file to `logstash-syslog-dns-template.json` and removed the PUT command in line 1, copied it to /etc/logstash/custom. I modified the /etc/nsm/securityonion.conf file by adding `--volume /etc/logstash/logstash-syslog-dns-template.json:/logstash-syslog-dns-template.json:ro` to the LOGSTASH_OPTIONS entry.

I restarted logstash, found out that it wasn't added. I tracked it down to a parsing error of `logstash-syslog-dns-template.json`. It turns out that Security Onion has a method for testing out custom templates called `so-elasticsearch-template-add`. When running that, I get the following error:

`{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "Malformed [mappings] section for type [dynamic], should include an inner object describing the mapping"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "Malformed [mappings] section for type [dynamic], should include an inner object describing the mapping"
  },
  "status": 400
}`

I am trying to find out how to fix that. Any suggestions?

Thanks :)

/klaus

**Comment by klausagnoletti** [comment]
Ok, fixed it. Please find the modified JSON template file pasted below (I couldn't attach it as a file):

I'll investigate later to see if it actuallly works now :)

logstash-syslog-dns-template.json

```
{
  "index_patterns": [
    "logstash-syslog-dns*"
  ],
  "mappings": {
   "doc":{
    "dynamic": "true",
      "properties" : {
        "@timestamp" : {
          "type" : "date"
        },
        "@version" : {
          "type" : "keyword"
        },
        "agent" : {
          "properties" : {
            "ephemeral_id" : {
              "type" : "text",
              "norms" : false,
              "fields" : {
                "keyword" : {
                  "type" : "keyword",
                  "ignore_above" : 256
                }
              }
            },
            "hostname" : {
              "type" : "text",
              "norms" : false,
              "fields" : {
                "keyword" : {
                  "type" : "keyword",
                  "ignore_above" : 256
                }
              }
            },
            "id" : {
              "type" : "text",
              "norms" : false,
              "fields" : {
                "keyword" : {
                  "type" : "keyword",
                  "ignore_above" : 256
                }
              }
            },
            "name" : {
              "type" : "text",
              "norms" : false,
              "fields" : {
                "keyword" : {
                  "type" : "keyword",
                  "ignore_above" : 256
                }
              }
            },
            "type" : {
              "type" : "text",
              "norms" : false,
              "fields" : {
                "keyword" : {
                  "type" : "keyword",
                  "ignore_above" : 256
                }
              }
            },
            "version" : {
              "type" : "text",
              "norms" : false,
              "fields" : {
                "keyword" : {
                  "type" : "keyword",
                  "ignore_above" : 256
                }
              }
            }
          }
        },
        "blocked_domain" : {
          "type" : "text",
          "norms" : false,
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "date" : {
          "type" : "date",
          "format" : "MMM  d HH:mm:ss||MMM dd HH:mm:ss"
        },
        "dns_forward_to" : {
          "type" : "ip",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "domain_request" : {
          "type" : "text",
          "norms" : false,
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "domain_response" : {
          "type" : "text",
          "norms" : false,
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "ecs" : {
          "properties" : {
            "version" : {
              "type" : "text",
              "norms" : false,
              "fields" : {
                "keyword" : {
                  "type" : "keyword",
                  "ignore_above" : 256
                }
              }
            }
          }
        },
        "geoip" : {
          "dynamic" : "true",
          "properties" : {
            "city_name" : {
              "type" : "text",
              "norms" : false,
              "fields" : {
                "keyword" : {
                  "type" : "keyword",
                  "ignore_above" : 256
                }
              }
            },
            "continent_code" : {
              "type" : "text",
              "norms" : false,
              "fields" : {
                "keyword" : {
                  "type" : "keyword",
                  "ignore_above" : 256
                }
              }
            },
            "country_code2" : {
              "type" : "text",
              "norms" : false,
              "fields" : {
                "keyword" : {
                  "type" : "keyword",
                  "ignore_above" : 256
                }
              }
            },
            "country_code3" : {
              "type" : "text",
              "norms" : false,
              "fields" : {
                "keyword" : {
                  "type" : "keyword",
                  "ignore_above" : 256
                }
              }
            },
            "country_name" : {
              "type" : "text",
              "norms" : false,
              "fields" : {
                "keyword" : {
                  "type" : "keyword",
                  "ignore_above" : 256
                }
              }
            },
            "dma_code" : {
              "type" : "long"
            },
            "ip" : {
              "type" : "ip"
            },
            "latitude" : {
              "type" : "half_float"
            },
            "location" : {
              "type" : "geo_point"
            },
            "longitude" : {
              "type" : "half_float"
            },
            "postal_code" : {
              "type" : "text",
              "norms" : false,
              "fields" : {
                "keyword" : {
                  "type" : "keyword",
                  "ignore_above" : 256
                }
              }
            },
            "region_code" : {
              "type" : "text",
              "norms" : false,
              "fields" : {
                "keyword" : {
                  "type" : "keyword",
                  "ignore_above" : 256
                }
              }
            },
            "region_name" : {
              "type" : "text",
              "norms" : false,
              "fields" : {
                "keyword" : {
                  "type" : "keyword",
                  "ignore_above" : 256
                }
              }
            },
            "timezone" : {
              "type" : "text",
              "norms" : false,
              "fields" : {
                "keyword" : {
                  "type" : "keyword",
                  "ignore_above" : 256
                }
              }
            }
          }
        },
        "host" : {
          "properties" : {
            "name" : {
              "type" : "text",
              "norms" : false,
              "fields" : {
                "keyword" : {
                  "type" : "keyword",
                  "ignore_above" : 256
                }
              }
            }
          }
        },
        "input" : {
          "properties" : {
            "type" : {
              "type" : "text",
              "norms" : false,
              "fields" : {
                "keyword" : {
                  "type" : "keyword",
                  "ignore_above" : 256
                }
              }
            }
          }
        },
        "ip_request" : {
          "type" : "ip"
        },
        "ip_response" : {
          "type" : "ip"
        },
        "log" : {
          "properties" : {
            "file" : {
              "properties" : {
                "path" : {
                  "type" : "text",
                  "norms" : false,
                  "fields" : {
                    "keyword" : {
                      "type" : "keyword",
                      "ignore_above" : 256
                    }
                  }
                }
              }
            },
            "offset" : {
              "type" : "long"
            }
          }
        },
        "logrow" : {
          "type" : "integer"
        },
        "message" : {
          "type" : "text",
          "norms" : false
        },
        "pid" : {
          "type" : "integer"
        },
        "pihole" : {
          "type" : "ip"
        },
        "program" : {
          "type" : "text",
          "norms" : false,
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "query_type" : {
          "type" : "text",
          "norms" : false,
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "request_from" : {
          "type" : "ip"
        },
        "source_fqdn" : {
          "type" : "text",
          "norms" : false,
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "source_host" : {
          "type" : "ip"
        },
        "source_port" : {
          "type" : "integer"
        },
        "tags" : {
          "type" : "keyword",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "type" : {
          "type" : "text",
          "norms" : false,
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        }
      }
  }
 }
}

```

**Comment by nin9s** [comment]
The Template is meant to be loaded via kibanas Dev console via a api call (the line with put you deleted).
Seems like you are confusing index pattern with template but im not sure

I guess security onion is some kind of special because I've never encountered your issues with native elk stack

**Comment by klausagnoletti** [comment]
Thanks for your reply.

Yeah, I know. Security Onion wants the index patterns via templates in Logstash, apparently. 

I get the same error in Logstash log. The newest theory is that there is a collison with the buildin template `logstash-*` so I will need to reindex the pihole log, I guess . This is the list of templates in Security Onion:
```
[
  ".kibana_task_manager",
  ".management-beats",
  ".ml-anomalies-",
  ".ml-config",
  ".ml-meta",
  ".ml-notifications",
  ".ml-state",
  ".monitoring-alerts",
  ".monitoring-beats",
  ".monitoring-es",
  ".monitoring-kibana",
  ".monitoring-logstash",
  ".triggered_watches",
  ".watch-history-9",
  ".watches",
  "kibana",
  "kibana_index_template:.kibana",
  "logstash",
  "logstash-*",
  "logstash-beats",
  "logstash-index-template",
  "logstash-ossec",
  "logstash-syslog-dns",
  "security-index-template",
  "security_audit_log"
```
I'll write again when I know more.

/klaus

**Comment by nin9s** [comment]
you should be able to apply the template to any index pattern so you could potentially substitute logstash-syslog-dns with "some-name"

```
PUT /_template/some-name
{
  "index_patterns": [
    "some-index-pattern*"
  ],
```

in your case this would be logstash* or logstash-*

**Comment by klausagnoletti** [comment]
Thanks

My plan was to come up with another index name and adjust both the template and the conf file accordingly. Would this approach provide a different outcome?

Sorry if this is a stupid question, I am frankly pretty new in any part of ELK.

Thanks

/klaus

**Comment by nin9s** [comment]
nope, that should work as you expect :)
just keep in mind that you need to define when to delete some indexes if they get to large. There is a tool called "curator" which can do this for you and imo its easier to setup if your index names get some date appended eg day/month/year

**Comment by klausagnoletti** [comment]
Just an update here. I have dropped Security Onion and gone with a vanilla, containerized ELK. That works better.
