### ISSUE TITLE
source_fqdn %{source_host}

### ISSUE THREAD

**Issue by awataszko** [nin9s/elk-hole#33]
Hi,

This is great. I've managed to get it almost working but for whatever reason, the filter isn't able to parse the source_fqdn correctly. all I'm getting is source_fqdn %{source_host}. 

Any ideas?

Thanks

**Comment by nin9s** [comment]
Try to refresh the index fields and verify that the logstash host can resolve dns. 

Does it occur for every single log line?

**Comment by awataszko** [comment]
Thanks - It was an issue with DNS. Resolved - thanks!
