### ISSUE TITLE
Kibana v7.7 throwing error about fielddata=true not being set

### ISSUE THREAD

**Issue by emanuelstanciu** [nin9s/elk-hole#38]
After completing the steps in the guide, I can see data flowing into Elasticsearch and data is flowing into the system with some graphs partially rendering
However, I get a specific error that fielddata=true is not set and this should be done

Can you please advise if I'm doing anything wrong?
<img width="1680" alt="Screenshot 2020-08-08 at 02 12 19" src="https://user-images.githubusercontent.com/2768779/89699124-d4292780-d91c-11ea-8af2-d04756ea6f31.png">
<img width="1675" alt="Screenshot 2020-08-08 at 02 08 17" src="https://user-images.githubusercontent.com/2768779/89699130-d7bcae80-d91c-11ea-967c-e2ee6d0e8d6e.png">

**Comment by nin9s** [comment]
Did you try to refresh the index fields list?

**Comment by emanuelstanciu** [comment]
Thanks @nin9s - that did the trick
interestingly I did this once manually, but in my multiple attempts of creating and recreating those indexes, must have missed it again.
I have a last hurdle now, geoip.location is not in the index, although visible in the template and I get this on the default dashboard:
<img width="1678" alt="Screenshot 2020-08-08 at 20 43 59" src="https://user-images.githubusercontent.com/2768779/89718653-3be08080-d9b8-11ea-806f-08c1d6187845.png">
Is there anything I'm missing again?

**Comment by nin9s** [comment]
Please re-index and try again 
https://github.com/nin9s/elk-hole/issues/31#issuecomment-628141809

**Comment by emanuelstanciu** [comment]
Great, thanks for all your help @nin9s
