### ISSUE TITLE
Elasticsearch 7.9 support

### ISSUE THREAD

**Issue by scj643** [nin9s/elk-hole#39]
Elasticsearch 7.9 has changed how templates work. Storing this data as a [datastream](https://www.elastic.co/guide/en/elasticsearch/reference/current/data-streams.html) would make the most sense.

**Comment by nin9s** [comment]
do we need paid x-pack features to [enable and configure](https://www.elastic.co/guide/en/ingest-management/current/ingest-management-troubleshooting.html) elastic agent for that to work?

**Comment by scj643** [comment]
We wouldn't use ingest manager since it is an experemental feature. Data streams are append optimized indecies that handle the backing indicies for you, compared to haveing indicies with dates appended to them. Datastreams are part of X-Pack basic.

**Comment by nin9s** [comment]
thanks, got the idea.

I think we first have to solve this

![image](https://user-images.githubusercontent.com/17455046/92126252-38e27f80-ee00-11ea-8983-796d89fc841a.png)

**Comment by nin9s** [comment]
@scj643 please test if this works for you: [data stream](https://github.com/nin9s/elk-hole/blob/dev/json/logstash-syslog-dns-data-stream-index.template_ELK7.9%2B.json)
