### ISSUE TITLE
DNS type=65 not being parsed by logstash - grok parse failure

### ISSUE THREAD

**Issue by aviationfan** [nin9s/elk-hole#42]
It seems that Apple has started sending DNS requests with `[type=65]`. Not sure why they are doing that, some think it is an attempt to circumvent certain types of DNS filtering or blocking. I was reading about an issue with Cloudflare here [Apple with iOS 14 pokes a hole in DNS filtering with query type 65](https://community.cloudflare.com/t/apple-with-ios-14-pokes-a-hole-in-dns-filtering-with-query-type-65/225029). It seems like it was introduced in iOS 14.

OpenDNS responds to these queries with REFUSED so I had to change to Cloudflare for now since they are handling these better now. 

As for elk-hole, I think we just need to add or modify the grok patterns in the logstash config file to take these into account. Wanted to raise the issue here to get a discussion going about it.

Here are some samples from my logs:

```
Dec  1 10:52:13 dnsmasq[322841]: 1669 192.168.1.62/56571 query[type=65] firebaseinstallations.googleapis.com from 192.168.1.62
Dec  1 10:52:12 dnsmasq[322841]: 1663 192.168.1.62/58019 query[type=65] firebase-settings.crashlytics.com from 192.168.1.62
Dec  1 10:52:12 dnsmasq[322841]: 1665 192.168.1.62/65285 query[type=65] discord.com from 192.168.1.62
Dec  1 10:52:13 dnsmasq[322841]: 1667 192.168.1.62/62390 query[type=65] firebasedynamiclinks.googleapis.com from 192.168.1.62
Dec  1 10:52:14 dnsmasq[322841]: 1675 192.168.1.62/55691 query[type=65] clients.l.google.com from 192.168.1.62
Dec  1 10:52:14 dnsmasq[322841]: 1673 192.168.1.62/54136 query[type=65] clients3.google.com from 192.168.1.62
Dec  1 10:52:14 dnsmasq[322841]: 1676 192.168.1.62/53467 query[type=65] app.adjust.com from 192.168.1.62
Dec  1 10:52:14 dnsmasq[322841]: 1679 192.168.1.62/54796 query[type=65] discordapp.com from 192.168.1.62
Dec  1 10:52:15 dnsmasq[322841]: 1681 192.168.1.62/58979 query[type=65] api-va.tiktokv.com from 192.168.1.62
Dec  1 10:52:15 dnsmasq[322841]: 1683 192.168.1.62/64174 query[type=65] weather-data.apple.com from 192.168.1.62
Dec  1 10:52:15 dnsmasq[322841]: 1685 192.168.1.62/60788 query[type=65] e28622.a.akamaiedge.net from 192.168.1.62
Dec  1 10:52:15 dnsmasq[322841]: 1687 192.168.1.62/51572 query[type=65] a2047.dscb.akamai.net from 192.168.1.62
Dec  1 10:52:16 dnsmasq[322841]: 1694 192.168.1.62/53788 query[type=65] cdn.discordapp.com from 192.168.1.62
Dec  1 10:52:16 dnsmasq[322841]: 1693 192.168.1.62/56943 query[type=65] a2047.mm2.akamai.net from 192.168.1.62
Dec  1 10:52:16 dnsmasq[322841]: 1691 192.168.1.62/60963 query[type=65] p16-sign-va.tiktokcdn.com from 192.168.1.62
Dec  1 10:52:15 dnsmasq[322841]: 1689 192.168.1.62/50422 query[type=65] a1893.b.akamai.net from 192.168.1.62
Dec  1 10:52:38 dnsmasq[322841]: 1712 192.168.1.62/65174 query[type=65] latency.discord.media from 192.168.1.62
```

**Comment by aviationfan** [comment]
Wow here are some more types in my logs. 

```
Jun 25 02:47:21 dnsmasq[416917]: 309455 192.168.1.102/57114 query[type=65479] static.ess.apple.com from 192.168.1.102
Jun 25 02:47:21 dnsmasq[416917]: 309456 192.168.1.102/52089 query[type=65479] staticess.g.aaplimg.com from 192.168.1.102
Jun 25 02:47:21 dnsmasq[416917]: 309458 192.168.1.102/50498 query[type=65479] identity.ess.apple.com from 192.168.1.102
Jun 25 02:47:21 dnsmasq[416917]: 309459 192.168.1.102/60722 query[type=65479] identity.ess-apple.com.akadns.net from 192.168.1.102
Jun 25 02:47:22 dnsmasq[416917]: 309461 192.168.1.102/53411 query[type=65479] p37-fmip.icloud.com from 192.168.1.102
Jun 25 02:47:22 dnsmasq[416917]: 309463 192.168.1.102/64993 query[type=65479] fmip.fe.apple-dns.net from 192.168.1.102
Jun 25 02:47:22 dnsmasq[416917]: 309465 192.168.1.102/62821 query[type=65479] gspe85-ssl.ls.apple.com from 192.168.1.102
Jun 25 02:47:25 dnsmasq[416917]: 309469 192.168.1.102/59004 query[type=65479] p37-sharedstreams.icloud.com from 192.168.1.102
Jun 25 02:47:25 dnsmasq[416917]: 309471 192.168.1.102/55812 query[type=65479] sharedstreams.fe.apple-dns.net from 192.168.1.102
Jun 25 02:47:29 dnsmasq[416917]: 309482 192.168.1.102/52169 query[type=65479] cf.iadsdk.apple.com from 192.168.1.102
Jun 25 02:47:29 dnsmasq[416917]: 309484 192.168.1.102/55565 query[type=65479] e4805.dsca.akamaiedge.net from 192.168.1.102
Jun 25 02:47:39 dnsmasq[416917]: 309491 192.168.1.102/50337 query[type=65479] us-east-1.blobstore.apple.com from 192.168.1.102
Jun 25 02:47:39 dnsmasq[416917]: 309493 192.168.1.102/65137 query[type=65479] store-006-lb.blobstore-apple.com.akadns.net from 192.168.1.102
Jun 25 02:47:41 dnsmasq[416917]: 309497 192.168.1.102/59978 query[type=65479] me.apple-dns.net from 192.168.1.102
Jun 25 02:47:41 dnsmasq[416917]: 309495 192.168.1.102/58363 query[type=65479] metrics.icloud.com from 192.168.1.102
Jun 25 02:47:55 dnsmasq[416917]: 309507 192.168.1.102/56945 query[type=65479] pds-prod.ess.apple.com from 192.168.1.102
```

**Comment by nin9s** [comment]
mh that somehow sounds familiar to me. Are you sure you are  using the most recent logstash config file? Because in my logs that does not lead to a grokparsefailure anymore.

```
# request - query type
 "^%{DNSMASQPREFIX} query\[%{DATA:query_type}\] %{FQDN:domain_request} from %{IP:request_from}$",

```

![image](https://user-images.githubusercontent.com/17455046/100785684-4b755080-3411-11eb-89a8-27da1b0bdc6f.png)

**Comment by aviationfan** [comment]
I am probably not using the latest logstash config file. I will pull the latest and compare mine.

**Comment by nin9s** [comment]
what in fact bothers me is the "`date`" field showing year 1970 for some reason?! Could you also crosscheck please?

**Comment by greengeek** [comment]
First love the work that you have done on this!

I just installed elk-hole with the latest stables of elasticsearch stack, pihole, and elk-hole.    I am using google as the dns.  I don't know if this is related as I am not seeing any "query_type" fields in kibana, but I am also getting tags.keyword:_grokparsefailure.  This is following the instructions on this website and using  the option for ndjson.  Instructions weren't very clear if I needed to also include the json, or if they would give me anything additional, so I didnt add those.  Currently only sending one system through the pi-hole. 

Here are some screenshots of the dashboard and a zoomed in version that shows the "DNS request/response type -pihole"  visualization showing the error, as well as a sample of the discovery window with tags.keyword: _grokparsefailure filter set to only show.

Related? Any ideas on what is happening?

![elk-hole discover](https://user-images.githubusercontent.com/47870136/102725844-0d17d680-42d7-11eb-8b38-fd4975158860.png)
![elk-hole dashboard](https://user-images.githubusercontent.com/47870136/102725845-0db06d00-42d7-11eb-8d64-76f66f416870.png)
![elk-hole visualization](https://user-images.githubusercontent.com/47870136/102725846-0db06d00-42d7-11eb-91fb-1d69a68c5214.png)

**Comment by nin9s** [comment]
@greengeek its not related. the message you see is simply because until now I was to lazy to write a grok pattern to filter out similar messages which only happen during dnsmasq startup. in this case _grokparsefailure happens because there is no source_host in the log message meaning it cannot be parsed.

You can ignore it as, its not relevant for logging dns requests
