### ISSUE TITLE
Dashboards Missing

### ISSUE THREAD

**Issue by ratnamg** [nin9s/elk-hole#43]
**Describe the bug**
I continuously get missing data in the dashboards. I have tried to refresh the index multiple times and I see 83 fields and not 79. 

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/75150446/100900131-21ab4080-3488-11eb-9037-1e8484e04753.png">

**Comment by nin9s** [comment]
what data is missing exactly?

**Comment by ratnamg** [comment]
<img width="1387" alt="image" src="https://user-images.githubusercontent.com/75150446/100900549-92eaf380-3488-11eb-99c2-18832d206b8a.png">

**Comment by nin9s** [comment]
Did you reindex after setting up everything?

**Comment by ratnamg** [comment]
Here is what I have done since the last post. Restarted from scratch

**1) I deleted the Dev Tool console.**
<img width="1387" alt="image" src="https://user-images.githubusercontent.com/75150446/100913570-9043ca80-3497-11eb-8307-a2064fd41a68.png">


**2) Deleted the logstash-syslog-dns- under Index Management.** 
<img width="1387" alt="image" src="https://user-images.githubusercontent.com/75150446/100913680-bbc6b500-3497-11eb-9304-37c66b7223b4.png">


3) Deleted the Index Pattern - logstash-syslog-dns-* under Index Pattern
<img width="1387" alt="image" src="https://user-images.githubusercontent.com/75150446/100913837-e9abf980-3497-11eb-9e07-a1960db2f64f.png">


Is there anything else to be done before I restart? 

To your question, I did reindex.

**Comment by nin9s** [comment]
It likely has something to do with the visualizations you may have/not have imported. 

Crosscheck the viz (names) used in the dashboard with the ones being imported in the viz menu of kibana. You may need to click the edit button after opening the dashboard

**Comment by ratnamg** [comment]
I believe you are correct.. I only see 3 visualizations. Imported. 

I have reimported the viz files again. Any other recommendations?

<img width="983" alt="image" src="https://user-images.githubusercontent.com/75150446/100949373-bf762e00-34cf-11eb-8685-5b42c4069de2.png">

**Comment by dk1010101** [comment]
i had to import from ndjson to get everything as json alone didn't work. have you tried that?
