### ISSUE TITLE
Excessive DNS querues from logstash

### ISSUE THREAD

**Issue by rsf123** [nin9s/elk-hole#44]
After setting up elk-hole, I'm seeing an excessive number of DNS queries coming from my ELK stack, ironically back to my pihole!  Its causing a skewed set of statistics creating 1000's of queries from the logstash process back to DNS server.

The only thing I have running on my logstash collector is the configuration for elk-hole.  I've tried commenting out the dns lines in the config:

    #dns {
    #  nameserver => "localhost"
    #  reverse => ["source_fqdn"]
    #  action => "replace"
    #  hit_cache_size => 10000
    #  hit_cache_ttl => 900
    #  failed_cache_size => 512
    #  failed_cache_ttl => 900
    #}

But this doesn't seem to make any difference.  I've narrowed it down to logstash by simply shutting down the logstash container and the excessive queries cease.

All of the queries appear to be very bizarre reverse DNS looksups that are appending my DNS search domain multiple times, and all result in an NXDOMAIN response:

` "message" => "Jan 30 18:01:19 dnsmasq[590]: 2930 1.2.3.4/36884 query[A] 6.5.4.3.in-addr.arpa.domain.net.domain.net.domain.net.domain.net.domain.net.domain.net from 1.2.3.4",`

In this case 1.2.3.4 is an obfuscated address to my ELK stack.

**Comment by nin9s** [comment]
you did restart logstash after commenting out, right?

mh commenting out should prevent elk-hole from trying to resolve the requesting source (as you already did). TBH I dont think elk-hole could be responsible for this especially because you prooved its sourced by logstash.

Looks like there may be a more general problem with dns in your local lan/logstash cfg?

**Comment by nin9s** [comment]
how does your resolv.conf on the logstash host look like?

```
cat /etc/resolv.conf
#domain unimatrix01.local
#search unimatrix01.local
#nameserver 192.168.254.251
nameserver 127.0.0.1
```

I dont have search domain but my pihole has, so it will get appended anyway.

**Comment by rsf123** [comment]
Correct, I did restart after making the changes to the config file.   My logstash instance ONLY handles inputs from the filebeats on my pihole, so I'm baffled by the continuous queries even after I comment out those lines.

My elk stack is containerized so the docker container for logstash is pointing to the docker DNS server and inherits the DNS search domain from my host.  I'm going to play with DNS settings there next and see if getting it to talk directly to the pihole DNS server instead of the docker DNS server makes a difference in the concatenation of search domains.

But either way I'm still seeing 1000+ queries every 10 minutes coming out of the logstash instance when it is receiving logs from the pihole.

**Comment by nin9s** [comment]
let me know if you've ruled out specifics in your infrastructure and to give me some time to think about the Potential possibility that elk-hole may be responsible

**Comment by rsf123** [comment]
I rebuilt an ELK stack on a different host and used the exact same versions elk-hole is tested up to (7.9.0)..  Several of the errors I was seeing have gone away (my previous stack was 7.10.2).

Now I'm seeing some different oddities when I re-enable DNS:
1) "HOST A" on my network will query for a server (e.g., presence.teams.microsoft.com)
2) When that log entry makes it from pihole --> filebeats --> logstash, the logstash makes the SAME query.  

So in effect, there's a duplicate query for every query made on the network now, which makes it appear that logstash is making hundreds to thousands of queries.

The other thing that is odd is on the dashboard, all of the visualizations EXCEPT "requests over time", "Requests vs piholed" and "percent piholed" are showing up with an "ERROR" on them.  When I look at those visualizations directly, it gives me an [esaggs] > Bad Request

Another thing I noticed is that when I imported the ndjson, it created a duplicate index pattern.  If I skip creation of the index pattern and import just the ndjson, the ndjson will create the index pattern, but I still get the visualization error.

**Comment by aviationfan** [comment]
I am seeing the very same thing. A few days ago I updated the logstash config file `20-dns-syslog.conf` to be the same as the current version in this repo. This is what I see for Saturday Jan 30, 2021

Logstash server entries in the pihole logs:
346,141

ALL other devices on the network including phones, tablets, macs, PCs, roku, appleTV and so on (≈ 25 clients)
221,954

So that means that my headless server that no one used to browse we made over 300K requests to pihole. All other devices combined for that 24 hours were just over 200K. This is not right. 

Is there an unintended loop happening?

**Comment by nin9s** [comment]
```
Now I'm seeing some different oddities when I re-enable DNS:

"HOST A" on my network will query for a server (e.g., presence.teams.microsoft.com)
When that log entry makes it from pihole --> filebeats --> logstash, the logstash makes the SAME query.
So in effect, there's a duplicate query for every query made on the network now, which makes it appear that logstash is making hundreds to thousands of queries.
```

Yes, thats expected while using the geoip plugin. We may should enable geoip caching, by just commenting out the the cache_size here:


`/etc/logstash/conf.d/20-dns-syslog.conf`
```
if [domain_request] {
        geoip {
          cache_size => "10000"
          source => "domain_request"
        }
      }
```

If I'm right, this should significantly decrease the amount of queries logstash is actually sending to pihole.


`So that means that my headless server that no one used to browse we made over 300K requests to pihole. All other devices combined for that 24 hours were just over 200K. This is not right.`

is this really a new behavior or could it be you have had that before?

**Comment by aviationfan** [comment]
I updated my config on Jan 26 and then reverted it today. Notice the change in volume over the last 7 days. Logstash goes from a few thousand a day to hundreds of thousands per day. I will try to figure out if it's just duplicating the DNS queries that the other clients did.

![image](https://user-images.githubusercontent.com/955527/106402717-086f3380-63e8-11eb-8e0b-2dbb88b8a2ad.png)

**Comment by nin9s** [comment]
> I updated my config on Jan 26 and then reverted it today. Notice the change in volume over the last 7 days. Logstash goes from a few thousand a day to hundreds of thousands per day.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/955527/106402717-086f3380-63e8-11eb-8e0b-2dbb88b8a2ad.png)
> 
> 


Do you have a diff of both cfg files? Which was the old version in your case?

**Comment by nin9s** [comment]
please filter your output to only requests and not everything from your logstash host like so:

`source_fqdn.keyword :"logstashhost.domain" and tags.keyword : "request and query type" `

**Comment by rsf123** [comment]
I'll circle back and play with some of these settings as time permits.   I've been exploring another option of trying to use packetbeats to gather the data.  I've been able to get the data into ELK that tells a similar story (at least when looking through it in the Discover panel) as the filebeat log tail.

With your permission, I'd like to form your dashboards and visualizations and try and tune them to display the same info based on packetbeats?
________________________________

**Comment by aviationfan** [comment]
I applied the query you asked for. The large bars are the "new" config here in the repo and the small ones are my older setup. I suspect the issues lie in the complex if/then/else logic which is causing logstash to duplicate the client queries.

![logstash_dns_queries_before_and_after_latest_config](https://user-images.githubusercontent.com/955527/106637936-8ba39d00-6540-11eb-8daf-3a95993c4598.png)

**Comment by rsf123** [comment]
So I tried to uncomment the geoip caching and it didn't make any difference.

@aviationfan any chance you can share the earlier version of the config file you're using?  I'd like to see if it also fixes the issue on my end.

**Comment by nin9s** [comment]
> So I tried to uncomment the geoip caching and it didn't make any difference.
> 
> @aviationfan any chance you can share the earlier version of the config file you're using? I'd like to see if it also fixes the issue on my end.

did you also comment the whole section?

```
if [domain_request] {
        geoip {
          cache_size => "10000"
          source => "domain_request"
        }
      }
```

**Comment by aviationfan** [comment]
Here is the conf file I am using with the extension txt added for safe upload.

[20-dns-syslog.conf.txt](https://github.com/nin9s/elk-hole/files/5914418/20-dns-syslog.conf.txt)

**Comment by nin9s** [comment]
As @aviationfans upload prooves the issue definetely sources from the geoip looking up domain names (and not only ips).
I'll will file a PR. For the time being delete every occurance of the geoip block in the file with the following two:

```
  if [ip_response] {
        geoip {
          cache_size => "10000"
          source => "ip_response"
        }
      }
	  
	   if [ip_request] {
        geoip {
          cache_size => "10000"
          source => "ip_request"
        }
      }
```

**Comment by nin9s** [comment]
@rsf123 can we close this?

**Comment by bwhitehead0** [comment]
@nin9s i realize this is closed, but was a PR filed already? i have the current master and i'm seeing the same issues. checking before i manually edit my config.

**Comment by nin9s** [comment]
Not sure as I'm on mobile right now but you can adapt the configuration file according to my last post above and it should work as expected.

Could you try and confirm if it's working for you please
