### ISSUE TITLE
filebeat Connection refused to logstash

### ISSUE THREAD

**Issue by EnlightedBitFox** [nin9s/elk-hole#47]
**Describe the bug**
Hello there,
i have the following problem:
After going through the steps about filebeat and logstash, i tested the connection between them via telnet ip:port from filebeat (running on raspberry) to logstash (running on a proxmox server as an ubuntu container).
The result are "Connection refused"
On the logstash server i did add a firewall rule for 5141 tcp, the same way i did for elasticsearch and kibana. Both are reachable via http or telnet.
Following is the output of the command "systemctl status logstash":
root@ElasticKibana:~# systemctl status logstash.service
* logstash.service - logstash
     Loaded: loaded (/etc/systemd/system/logstash.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2022-06-29 15:39:00 UTC; 4s ago
   Main PID: 3958 (java)
      Tasks: 15 (limit: 18984)
     Memory: 256.8M
        CPU: 7.546s
     CGroup: /system.slice/logstash.service
             `-3958 /usr/share/logstash/jdk/bin/java -Xms1g -Xmx1g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly >

Jun 29 15:39:00 ElasticKibana systemd[1]: Started logstash.
Jun 29 15:39:00 ElasticKibana logstash[3958]: Using bundled JDK: /usr/share/logstash/jdk
Jun 29 15:39:01 ElasticKibana logstash[3958]: OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed i>
lines 1-13/13 (END)

On a previous setup it all worked....

Maybe anyone can help me out. Thanks

**Comment by nin9s** [comment]
refused means there was an active „go away“ reply from the destination. Could you check if logstash is really listening via 
`sudo netstat -tlnp | grep logstash`
