### ISSUE TITLE
piholed percent dashlet show 0% filter ratio

### ISSUE THREAD

**Issue by aviationfan** [nin9s/elk-hole#5]
The guage showing percentage piholed is indication 0% when it should have some number greater than zero. This happens in the settings for Visualize / piholed percent - pihole

If the time frame selected has empty values or no data then the calculation goes to zero. If I pick a time frame where there is data for the entire time frame then it shows a number that makes more sense. My data only goes up to the previous day and is not yet being collected from the pihole in real-time so If I select "Last 7 days" most of the current day has no data.

**Expected behavior**
Percentage is calculated for any time frame

**Screenshots**
Added 1 screen shot.

ELK stack details
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
Elasticsearch 6.7
Kibana 6.7.1
Logstash 6.7
filebeat version 6.2.4 (amd64), libbeat 6.2.4

**Desktop (please complete the following information):**
Mac OS 10.13.6
Chrome Version 74.0.3729.157 

![Pasted_Image_5_21_19__8_16_AM](https://user-images.githubusercontent.com/955527/58106502-738dbd80-7ba5-11e9-8df1-38df677a582e.png)

**Comment by nin9s** [comment]
as far as I remember this is expected behaviour due to the fact the gauge is working e.g. its always showing the last value.
Let me crosscheck that at the elastic docs, I will post back here as soon as I find it.

**Comment by aviationfan** [comment]
I guess that makes sense now that I know the gauge is working as designed. I am thinking I might want a different one for my purposes and will explore my own

**Comment by nin9s** [comment]
If you ever find a good alternative don't hesitate to give me a hint :)

JJ Welch <notifications@github.com> schrieb am Di. 21. Mai 2019 um 21:17:

**Comment by nin9s** [comment]
@aviationfan could you have a look at [https://github.com/nin9s/elk-hole/commit/dd6307cb94dc16104f43415d11b29de22d9ff726](url) please
