### ISSUE TITLE
Visualizations not correctly import in Kibana 7.17.21

### ISSUE THREAD

**Issue by ysi** [nin9s/elk-hole#50]
**Describe the bug**
When I import visualization json into Kibana 7.12, only few of them are really imported. Heatmap, table, and other are not imported at all. I can't see them in Visualize Library.
By try to import only "DNS top domains - pihole", the import says that it import nothing.

**To Reproduce**
On 7.17.21 Kibana version

**Comment by nin9s** [comment]
What caused the issue?
