### ISSUE TITLE
Heat Map missing from 'elk-hole - vis.json'

### ISSUE THREAD

**Issue by aviationfan** [nin9s/elk-hole#7]
When I open the dash board the heatmap shows an error looking for GUID of the heatmap visualization.

I looked at the latest 'elk-hole - vis.json' and the expected section is missing.

**Comment by nin9s** [comment]
thanks, that was my fault - renamed the heatmap vis so I wont forget to export it again
https://github.com/nin9s/elk-hole/blob/master/elk-hole%20-%20vis.json
