### ISSUE TITLE
Unable to import dash or vis json files into kibana 6.7

### ISSUE THREAD

**Issue by aviationfan** [nin9s/elk-hole#8]
The new updates seem to support only 7.x of Kibana. I reset my ELK stack to try out a newer setup and realized that I cannot import the json files in the older version.

Just opened the issue as an FYI. Might need a way to import the proper version of the files that matches the version of Kibana, or just let folks know that only 7 and up are supported.

**Comment by nin9s** [comment]
Thanks, really appreciate your contribution!
I will reupload the 6x jsons again.

**Comment by aviationfan** [comment]
I hope you don't mind my testing this project. I do testing for a living and cannot help but find stuff that I would change or fix

**Comment by nin9s** [comment]
No, your help is really appreciated in every single case. This is what makes github and working together on projects so valuable.

As I'm not a real github expert so far, I hope the new 6.x files are the recent 6.x version I had previously overwritten ^_^

Thanks again!
